encoding: utf-8

# SEO相关信息
title: BUG修了吗
description: Raph Blog
keywords: Blog,Java,Html,JavaScript,Code,
author: raphice
footerText: 'Host By GitHub'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
# domainUrl: 'https://errortao.github.io/'
baseurl: ''

# 菜单
menu:
  - title: 首页
    url: /
  - title: 后续计划
    url: /pages/plan.html

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
gems: [jekyll-paginate]

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
# links:
#   - title: site-name
#     url: site-url

